### ISSUE TITLE
Can't find the bag.

### ISSUE THREAD

**Issue by luolin2611** [underwindfall/RNScanCode#1]
hi 
I use the following command

1.
        npm install --save react-native-scanview-barcode
Error information
        npm ERR! 404 Not Found: react-native-scanview-barcode@latest

2.
       yarn add react-native-scanview-barcode
Error information：
      error Couldn't find package "react-native-scanview-barcode" on the "npm" registry.

**Comment by underwindfall** [comment]
hello there, 
 Really sorry for not responding such late. The reason u could not use install package because I was never publish this dependency.  However you could just try
`yarn add github:underwindfall/RNScanCode`
